export const IpcMethod = {
  ProjectCreate: 'project.create',
  ProjectList: 'project.list',
  ProjectOpen: 'project.open',
  ProjectClose: 'project.close',
  ProjectRename: 'project.rename',
  ProjectDelete: 'project.delete',

  SessionCreate: 'session.create',
  SessionList: 'session.list',
  SessionOpen: 'session.open',
  SessionRename: 'session.rename',
  SessionReset: 'session.reset',
  SessionDelete: 'session.delete',
  SessionAirdrop: 'session.airdrop',
  SessionWarpToSlot: 'session.warpToSlot',
  SessionWarpByTime: 'session.warpByTime',
  SessionExpireBlockhash: 'session.expireBlockhash',
  SessionGetClock: 'session.getClock',

  ProgramAdd: 'program.add',
  ProgramAddLocal: 'program.addLocal',
  ProgramList: 'program.list',
  ProgramRemove: 'program.remove',
  ProgramRefreshElf: 'program.refreshElf',
  ProgramListBuiltins: 'program.listBuiltins',
  ProgramSetLabel: 'program.setLabel',
  ProgramListInstructions: 'program.listInstructions',
  TxEncodeIx: 'tx.encodeIx',
  TxDecodeIx: 'tx.decodeIx',

  AccountAdd: 'account.add',
  AccountAddBulk: 'account.addBulk',
  AccountList: 'account.list',
  AccountGet: 'account.get',
  AccountDecode: 'account.decode',
  AccountSetRaw: 'account.setRaw',
  AccountSetLabel: 'account.setLabel',
  AccountRemove: 'account.remove',
  AddressDeriveAta: 'address.deriveAta',
  AddressDerivePda: 'address.derivePda',

  PatchCreate: 'patch.create',
  PatchList: 'patch.list',
  PatchToggle: 'patch.toggle',
  PatchRemove: 'patch.remove',
  PatchPromote: 'patch.promote',
  PatchDemote: 'patch.demote',

  TxBuild: 'tx.build',
  TxSend: 'tx.send',
  TxSimulate: 'tx.simulate',
  TxReplay: 'tx.replay',
  TxHistory: 'tx.history',
  TxHistoryClear: 'tx.historyClear',
  TxTemplateSave: 'tx.templateSave',
  TxTemplateList: 'tx.templateList',
  TxTemplateDelete: 'tx.templateDelete',
  WorkflowSave: 'workflow.save',
  WorkflowList: 'workflow.list',
  WorkflowDelete: 'workflow.delete',
  WorkflowRun: 'workflow.run',

  SnapshotSave: 'snapshot.save',
  SnapshotRestore: 'snapshot.restore',
  SnapshotFork: 'snapshot.fork',
  SnapshotDiff: 'snapshot.diff',

  IdlAttach: 'idl.attach',
  IdlDetach: 'idl.detach',
  IdlList: 'idl.list',
  IdlFetchOnchain: 'idl.fetchOnchain',

  KeypairGenerate: 'keypair.generate',
  KeypairImport: 'keypair.import',
  KeypairList: 'keypair.list',
  KeypairDelete: 'keypair.delete',
  KeypairReseal: 'keypair.reseal',
  KeypairExportSecret: 'keypair.exportSecret',

  RpcUpsertEndpoint: 'rpc.upsertEndpoint',
  RpcListEndpoints: 'rpc.listEndpoints',
  RpcDeleteEndpoint: 'rpc.deleteEndpoint',
  RpcServerStart: 'rpcServer.start',
  RpcServerStop: 'rpcServer.stop',
  RpcServerStatus: 'rpcServer.status',

  ScriptSave: 'script.save',
  ScriptList: 'script.list',
  ScriptRun: 'script.run',
  ScriptDelete: 'script.delete',
} as const;

export type IpcMethod = (typeof IpcMethod)[keyof typeof IpcMethod];

export const IpcEvent = {
  Log: 'log',
  Trace: 'trace',
  ProjectChanged: 'project-changed',
  SessionChanged: 'session-changed',
  TxCompleted: 'tx-completed',
} as const;

export type IpcEvent = (typeof IpcEvent)[keyof typeof IpcEvent];
